name=${project.artifactId}
description=Opensearch Javacafe Plugin. 
version=${project.version}
classname=org.opensearch.plugin.analysis.JavacafePlugin
opensearch.version=${opensearch.version}
java.version=21
